In [56]:
#pip install pandas

In [39]:
#Pandas Tutorial
#Pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1',"Row2","Row3","Row4","Row5"],columns=["Column1","Column2","Column3","Column4"])
df.head()

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [4]:
#df.to_csv("Test1.csv")

In [43]:
#accessing the elements
# 1 .loc(specifically for rows)  2 .iloc (works with rows and columns)

df.loc["Row1"]

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64

In [1]:
#type(df.loc["Row1"])

In [45]:
df[["Column1","Column2"]]

      Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

In [46]:
df.iloc[:,1:]

      Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [2]:
#type(df.iloc[:,1:]) #gives dataframe because more than one row and more than one column if i use only one column it will be series

In [48]:
df.iloc[0:1,1]                #only one row no column

Row1    1
Name: Column2, dtype: int64

In [3]:
#type(df.iloc[0:1,1])

In [50]:
df.iloc[:,0:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [51]:
df.iloc[:,0:].values.shape

(5, 4)

In [52]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [53]:
df

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [54]:
df["Column1"].value_counts()

Column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [62]:
df["Column1"].unique() #checks for unique values

array([ 0,  4,  8, 12, 16])

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes