In [3]:
#pip install pandas

In [4]:
import pandas as pd

In [123]:
df = pd.read_csv("placement.csv",index_col=0)
df.head()

   cgpa     iq  placement
0   6.8  123.0          1
1   5.9  106.0          0
2   5.3  121.0          0
3   7.4  132.0          1
4   5.8  142.0          0

In [119]:
df = pd.read_csv("placement.csv",dtype=object,index_col=1) # or float and index_col changes the index for the dataset
df.head()

     Unnamed: 0     iq placement
cgpa
6.8           0  123.0         1
5.9           1  106.0         0
5.3           2  121.0         0
7.4           3  132.0         1
5.8           4  142.0         0

In [106]:
df["cgpa"][1] #accessing using index

'5.9'

In [93]:
df = pd.read_csv("placement.csv",usecols=["cgpa","iq"])
df.head()

   cgpa     iq
0   6.8  123.0
1   5.9  106.0
2   5.3  121.0
3   7.4  132.0
4   5.8  142.0

In [114]:
df.dtypes

Unnamed: 0      int64
cgpa          float64
iq            float64
placement       int64
dtype: object

In [112]:
df=pd.read_csv("placement.csv",dtype={'placements':int,'cgpa':float})
df["cgpa"]

0     6.8
1     5.9
2     5.3
3     7.4
4     5.8
     ...
95    4.3
96    4.4
97    6.7
98    6.3
99    6.2
Name: cgpa, Length: 100, dtype: float64

In [115]:
df.dtypes

Unnamed: 0      int64
cgpa          float64
iq            float64
placement       int64
dtype: object

In [94]:
#test=pd.read_csv("Test1.csv",sep=';')
#test

In [95]:
#df["cgpa"].unique()

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cgpa    100 non-null    float64
 1   iq      100 non-null    float64
dtypes: float64(2)
memory usage: 1.7 KB

In [97]:
df.isnull().sum()

cgpa    0
iq      0
dtype: int64

In [98]:
#df.describe()

In [99]:
#df["cgpa"].value_counts()

In [100]:
from io import StringIO, BytesIO

In [101]:
data = ('col1,col2,col3\n'
            'x,y,1\n'
            'a,b,2\n'
            'c,d,3')

In [102]:
type(data)

str

In [103]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [124]:
#Text Data
data='a,b\n"hello, \\"John\\", nice to see you",5'
pd.read_csv(StringIO(data),escapechar='\\')

                                a  b
0  hello, "John", nice to see you  5

In [127]:
#pd.read_csv("https://download.bls.gov/pub/time.series/cu/cu.item", sep='\t')

In [129]:
d= pd.read_csv("cu.item", sep='\t')
d

,item_code,item_name,display_level,selectable,sort_sequence
0,AA0,All items - old base,0,T,2
1,AA0R,Purchasing power of the consumer dollar - old ...,0,T,400
2,SA0,All items,0,T,1
3,SA0E,Energy,1,T,375
4,SA0L1,All items less food,1,T,359
...,...,...,...,...,...
395,SSEA011,College textbooks,3,T,314
396,SSEE041,Smartphones,4,T,335
397,SSFV031A,Food at elementary and secondary schools,3,T,122
398,SSGE013,Infants' equipment,3,T,356
399,SSHJ031,Infants' furniture,3,T,165