In [3]:
#pip install pandas

In [6]:
import pandas as pd

In [44]:
df = pd.read_csv("placement.csv",index_col=0,nrows=100,on_bad_lines='skip')
#index_col changes the index for the dataset
df       
# OR warn when skipping bad lines
#df = pd.read_csv("data.csv", on_bad_lines='warn')

#for the dates for changing in datetime[64] from object or string
#df = pd.read_csv("data.csv", parse_dates=['date'])

    cgpa     iq  placement
0    6.8  123.0          1
1    5.9  106.0          0
2    5.3  121.0          0
3    7.4  132.0          1
4    5.8  142.0          0
..   ...    ...        ...
95   4.3  200.0          0
96   4.4   42.0          0
97   6.7  182.0          1
98   6.3  103.0          1
99   6.2  113.0          1

[100 rows x 3 columns]

In [46]:
df = pd.read_csv("placement.csv",dtype=object,skiprows=[1,3]).info() # or float and skiprows removes the given rows
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  98 non-null     object
 1   cgpa        98 non-null     object
 2   iq          98 non-null     object
 3   placement   98 non-null     object
dtypes: object(4)
memory usage: 3.2+ KB

In [47]:
#df["cgpa"][1] #accessing using index

In [ ]:
df = pd.read_csv("placement.csv",usecols=["cgpa","iq"])
df.head()

In [10]:
df.dtypes

Unnamed: 0    object
iq            object
placement     object
dtype: object

In [11]:
df=pd.read_csv("placement.csv",dtype={'placements':int,'cgpa':float})
df["cgpa"]

0     6.8
1     5.9
2     5.3
3     7.4
4     5.8
     ...
95    4.3
96    4.4
97    6.7
98    6.3
99    6.2
Name: cgpa, Length: 100, dtype: float64

In [12]:
df.dtypes

Unnamed: 0      int64
cgpa          float64
iq            float64
placement       int64
dtype: object

In [13]:
#test=pd.read_csv("Test1.csv",sep=';')
#test

In [14]:
#df["cgpa"].unique()

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  100 non-null    int64
 1   cgpa        100 non-null    float64
 2   iq          100 non-null    float64
 3   placement   100 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 3.3 KB

In [16]:
df.isnull().sum()

Unnamed: 0    0
cgpa          0
iq            0
placement     0
dtype: int64

In [17]:
#df.describe()

In [18]:
#df["cgpa"].value_counts()

In [19]:
from io import StringIO, BytesIO

In [20]:
data = ('col1,col2,col3\n'
            'x,y,1\n'
            'a,b,2\n'
            'c,d,3')

In [21]:
type(data)

str

In [22]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [28]:
#Text Data
data='a,b\n"hello, \\"John\\", nice to see you",5'
pd.read_csv(StringIO(data),escapechar='\\',names=['sno','first','second'],index_col='sno') 
#index col is used for chnaging the index of dataset and names are used for naming the columns

                               first  second
sno
a                                  b     NaN
hello, "John", nice to see you     5     NaN

In [5]:
#pd.read_csv("https://download.bls.gov/pub/time.series/cu/cu.item", sep='\t')

In [129]:
d= pd.read_csv("cu.item", sep='\t')
d

,item_code,item_name,display_level,selectable,sort_sequence
0,AA0,All items - old base,0,T,2
1,AA0R,Purchasing power of the consumer dollar - old ...,0,T,400
2,SA0,All items,0,T,1
3,SA0E,Energy,1,T,375
4,SA0L1,All items less food,1,T,359
...,...,...,...,...,...
395,SSEA011,College textbooks,3,T,314
396,SSEE041,Smartphones,4,T,335
397,SSFV031A,Food at elementary and secondary schools,3,T,122
398,SSGE013,Infants' equipment,3,T,356
399,SSHJ031,Infants' furniture,3,T,165

#**Converters** used for converting to short names

In [48]:
def rename(name):
    if name=="Royal Challengers Banglore":
        return "RCB"
    else:
        return name

In [57]:
rename("Royal Challengers Banglore")

'RCB'

In [58]:
#pd.read_csv("IPL Matches.csv",converters={'team1':rename})

In [59]:
#na_values for NaN or used for null values or not present
#pd.read_csv("aug_train.csv",na_values=['Male']) or '-'

In [69]:
#Loading Data in chunks
pp= pd.read_csv('aug_train.csv',chunksize=5000)

In [71]:
for chunks in pp:
    print(chunks.shape)

(5000, 14)
(5000, 14)
(4158, 14)